# container orchestration
services:
  ui:
    image: my-website-ui
    container_name: my-website-ui
    pull_policy: never
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: client
      args:
        - API_URL=$API_URL
    ports:
      - 80:80
    networks:
      - local-network
    depends_on:
      - server
  
  server:
    image: my-website-server
    container_name: my-website-server
    pull_policy: never
    build:
      context: ./server
      dockerfile: Dockerfile
      target: server
    environment:
      - SURREAL_REMOTE_URL=$SURREAL_REMOTE_URL
      - SURREAL_DB=$SURREAL_DB
      - SURREAL_USER=$SURREAL_USER
      - SURREAL_PASSWORD=$SURREAL_PASSWORD
      - SURREAL_NAMESPACE=$SURREAL_NAMESPACE
      - UI_URL=$UI_URL
      - MANAGER_URL=$MANAGER_URL
      - API_KEY=$API_KEY
    ports:
      - 8000:8000
    networks:
      - local-network
  
networks:
  local-network:
      driver: bridge
    